### ISSUE TITLE
Mysql doesn't use UUID identification

### ISSUE THREAD

**Issue by PhanaticD** [Borlea/EchoPet#104]
Looking in the database it shows my name not UUID https://gyazo.com/879f0abc421a6d9615ef1df7b10d70ba

**Comment by Borlea** [comment]
UUIDMigration.getIdentificationFor(Player) should be used.

No clue if I should just remove the column name.. or add a 2nd one for uuid.. Both have a downside.
First loses data, second requires two table lookups.

**Comment by Borlea** [comment]
2468dd5042b6028aa0a3b1aa6134d97e2ae85464 Is a possible fix.. Could this be retested with online mode enabled, cleared db, and latest build?

**Comment by PhanaticD** [comment]
works :D
