### ISSUE TITLE
Hidden pet reappearing after teleporting to a new location.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#108]
EchoPet dev 13
Paper dev 881 (Spigot 1.10.2)
ProtocolLib dev 325

@Borlea 
Pets that are hidden (`/pet hide` or `/pet toggle`) reappear when you teleport somewhere else. Shouldn't the pet visibility status persist on teleports so it isn't tracking the entity when it shouldn't be visible / loaded by player request?

Behavior possibly broke in this commit. https://github.com/Borlea/EchoPet/commit/7ed9cffc9841ae6a4eef43a5b2f5d4ca0401f197

**Comment by mibby** [comment]
Confirmed fixed, thanks!

**Comment by mibby** [comment]
@Borlea Apologies, seems I closed it prematurely. While the pet no longer spawns while hidden when you teleport around now, it appears when you and respawn.

**Comment by Borlea** [comment]
@mibby Is this resolved? Will be closed soon if no response.

**Comment by mibby** [comment]
Seems to be fine as of dev 31. A hidden pet does not reappear when teleporting to a new location or respawning from a death. A hidden pet only reappears when relogging, but I assume that is intended behavior since pet state isn't written to the pets yml file.
