### ISSUE TITLE
Update to 1.11-R0.1

### ISSUE THREAD

**Issue by Borlea** [Borlea/EchoPet#114]
Not 100% sure on the best way to setup EchoPet to support 1.10 and 1.11 but I have a 'decent' idea which should hopefully work.

I released a system in one of the 1.10 builds to make it so 1.10 mobs didn't display 1.9, I might do the same for 1.11 but also add it in for PetData. With this I can disable certain settings being shown in the inventory of pets(Like horse types) as they would be a whole different egg.

Another idea is to do a change to check if the server is 1.11+ and spawn the proper mob when certain petdata is set.

Just gonna get the basics working and see what is gonna be the best option. The clutter of eggs in the inventory doesn't seem like the best idea.

- [x] Fix any issues related to how Minecraft handles spawning mobs, changing mobs, etc.
- [x] Do a quick check to find any mobs that might have changed DataWatchers.
- [x] Support new entity types(horse, skele, zombie, guardian)
- [x] Add new mobs(Illager, Vindicator, Evoker, Vex, Llama)
- [x] Modify how we spawn the custom entity to prevent conflicts
- [x] Update config with new Pets
- [x] Update package & methods to 1.11
- [x] Fix pet selector gui as its.. overloaded
- [x] Fix husks and strays having the wrong sounds
- [x] /pet slime cow doesn't spawn the bottom pet(slime). Relog fixes.

**Comment by TheIntelloBox** [comment]
Is the plugin fully compatible with new mobs ?

**Comment by drekryan** [comment]
@TheIntelloBox I'd say not yet.. going to most likely take a bit longer for that.

**Comment by TheIntelloBox** [comment]
When do you think ? December ?

**Comment by Borlea** [comment]
I would expect by the end of the weekend. A 100% stable build might take a bit longer. Shouldn't be long

**Comment by TheIntelloBox** [comment]
Okay.

**Comment by Borlea** [comment]
Soo some of the llama settings work. I prob spent well over an hour frustrated by this gui system dsh has made.. I'm most likely just gonna rewrite it all and wont be fixing llama carpet/variant setting till after that.

**Comment by TNTUP** [comment]
Entities are invisible on my side, running on Paper. Could it be the issue?

**Comment by TheIntelloBox** [comment]
@Borlea The plugin will works fine with new entities ?

**Comment by TNTUP** [comment]
@Borlea 

1. Tested the Llama, Driving it, setting llama's color, and llama variant. They all works as intended.
2. Tested the Vex. Couldn't fly with it, had to regenerate the config and retried and I can fly. But, I can't go down so I dismount and I let it teleport to me and fly again. There's no setting to make it charged, guessing it's planned in the near future?
3. The command /pet <pet> <pet> does not work in 1.11, tried on my productive server on 1.10.2, works.
4. As the issue in #120, I've reproduced it in Build 23, there's just the Human pet shown, the others are gone. I can copypaste from my backed config to see them back.
5. All pets which are 2-blocks height can pass in 1-block height holes, should be 2-block height, is it intended? Spiders are 1-block height can pass in 1/2 block height hole heh xD
6. Husk/Stray uses default zombies/skeletons sounds. 
7. Enderman glitches with 1-block height hole (Teleporting endermans)
8. I remember way before (I guess it was in 1.8's, chickens were able to fly down (like normal chickens falling off)
9. (Same for the 8.) but spiders, they were able to climb walls. I guess it got removed for a reason (It was on DSH's build)
10. Horses pets works. :D But driving them doesn't update the client, but anyone can see us driving like normal. Guessing it's now client sided now?
11. Pigs are used to be broken in 1.10, they works in 1.11. So horses are broke :(

I guess I tested what I tried, if you have ideas to test, let me know :)

**Comment by Borlea** [comment]
holy shit horses do work in 1.11 wtf

**Comment by TheIntelloBox** [comment]
I think too.
Do you think the release, will be before December or after ?

**Comment by Borlea** [comment]
@TheIntelloBox No clue.. Need to make sure no crashes exist and the main features of 1.11 are added. Should be sometime this month.

**Comment by Borlea** [comment]
Anyone have any information on Vex? I understand he can be in a 'charged'/'powered' state adding red lines to the model.

But on the wiki http://minecraft.gamepedia.com/Vex with the picture 'A vex attacking' the vex looks human size and I'm unable to find where I would set that.

**Comment by drekryan** [comment]
#118 is the only real showstopper for me right now. Besides a minor issue with Citizens I need to report to them and the incompatibility between Citizens and EchoPet is all I need to get sorted for my SkyBlock server to run 1.11. Was surprised as I was expecting a much more annoying update. Thanks for your work :) With all the entity changes for 1.11 makes an update for a plugin like this a hassle for sure.

**Comment by drekryan** [comment]
Well I guess the overloaded GUI is kinda high priority for me since I don't think all the pet currently fit there. I don't think the Vex or Vindicator are in that list currently. And using that last row did sacrifice the other name pet, ride, hat, toggle, etc. buttons. Was going to PR it myself but that part of the code was a mess so I didn't bother lol

**Comment by Borlea** [comment]
@drekryan 
EchoPet works on build 1426 of Citizens before the 'Modify EntityTypes hooks to be less invasive' commit
But build 1428 after that commit + an additional fix to allow it to build(1427) causes pets to be invisible.

and for the pet selector gui.. I'm most likely going to need to add pages which is definitely gonna be a bit of a challenge with the 'mess' it is.

**Comment by drekryan** [comment]
@Borlea looks to be controlled by LifeTicks I think so I don't think it's something that can be set. Idk

![](http://i.imgur.com/Z9FSKh2.jpg)

(Bottom of page) http://minecraft.gamepedia.com/Chunk_format#Entity_format

**Comment by Borlea** [comment]
@drekryan Life ticks is actually 2 separate fields in EntityVex.
'bw' = starve is enabled, so every 20 ticks it'll take 1 heart of damage
'bx' = current amount of lifeticks
https://goo.gl/IsEYOm

**Comment by drekryan** [comment]
Do they only turn red when they take damage?

**Comment by Borlea** [comment]
'When they are attacking, they glow red and lunge at their target'
So whenever you attack a Vex or its spawner(Evoker) the vex will turn red, lunge and attack

**Comment by drekryan** [comment]
@Borlea While I am here I figured I would ask you a question regarding EchoPet. I have been wanting to make it so the pets have a bit more distance between the player. In the config files I tried increasing the stopFollowDistance thinking that would make them stop further away. I just dont like how close the pets get. They get to about one block distance to you, right on top of your feet which most times makes the pet more annoying and in your way than a companion. Is that number supposed to be the number of blocks from you they stop or am I misunderstanding that option. If it is supposed to work that way it seems it doesn't have any effect. Is there a way to make the pets distance themselves from you a bit more?

**Comment by TNTUP** [comment]
Edited my post, I'll strike what is fixed. You're the best @Borlea :P

**Comment by Borlea** [comment]
@drekryan It should work, you might have to drastically increase it. This is the method used to check the distance between the pet & the owner.
  public double h(Entity entity) {
    double d0 = this.locX - entity.locX;
    double d1 = this.locY - entity.locY;
    double d2 = this.locZ - entity.locZ;
    
    return d0 * d0 + d1 * d1 + d2 * d2;
  }

**Comment by Borlea** [comment]
@drekryan soon http://i.imgur.com/12Iaoog.png

**Comment by drekryan** [comment]
Lol so close

**Comment by TNTUP** [comment]
@Borlea remove the human pet? It's not even supported since 1.9 and fewer... then you can fit the vex inside. Unless i'm wrong and Human pets works (w/ Citizens?)

**Comment by drekryan** [comment]
I actually think Citizens 2.0.21 or whatever it is supports it but it may still be disabled internally by EchoPet. Would only be a temporary thing as well until 1.12 rolls around and adds a new furry :)

**Comment by TNTUP** [comment]
@drekryan Everytime I check pets, the Human always says it's not compatible with my server version, so I guess it can be freely removed, unless it has Citizens2 support in it, so idk then XD

**Comment by drekryan** [comment]
@TNTUP Yeah I think Citizens fixed it so it could work but I think EchoPet still has is disabled. @Borlea may be able to re-add it but yeah never have seen that much need for the Human pet as it was but thats just my opinion. Latest developer builds of Citizens 2 supports it if Im reading on of the issues over on their report correctly. I don't want to link and reference it but issue nine hundred and eighty four on their repo is where I saw brief mention of it. Haven't tried it myself though.

**Comment by TNTUP** [comment]
@drekryan Nice^^ :)

**Comment by Borlea** [comment]
Found a little bug and the Vex isn't alone :D http://i.imgur.com/YaR4BOb.png

**Comment by drekryan** [comment]
@Borlea Were you missing the vindicator or evoker?

**Comment by Borlea** [comment]
Vindicator

**Comment by TNTUP** [comment]
They could be catogorized by mob (Animals, Monsters or whatever xD)

**Comment by Borlea** [comment]
At this point I might as well setup an irc.. We are using this github issue as an instant messenger

**Comment by TNTUP** [comment]
Yeah, good idea^^ @Borlea It will be on esper or spi.gt one?

**Comment by Borlea** [comment]
Whatever one is easier.. I barely use irc

**Comment by drekryan** [comment]
@Borlea lol thought the same thing lol.. oh well ;) and yeah I've you do setup IRC I do frequent both the Spigot and Esper ones.. pretty much signed in 24/7 on them

**Comment by Borlea** [comment]
I registered #echopet under my name on whatev irc https://www.spigotmc.org/pages/irc/ this is. From my understanding that is all I need to do. Guess I'll setup a irc client on my comp and make sure to join it

**Comment by TheIntelloBox** [comment]
When I write /pet Shulker it says nothing, is it normal ?

**Comment by Borlea** [comment]
Closing as the main conversion to 1.11 is complete.

Shulker box will/may never be added due to it being 'special' I might look into it again in my freetime sometime in the future.

**Comment by TheIntelloBox** [comment]
I speak about the shulker, not the shulkerbox. xD
