### ISSUE TITLE
[1.11] EchoPet with Citizens Dev build #1428+ causes invisible pets/npcs

### ISSUE THREAD

**Issue by drekryan** [Borlea/EchoPet#118]
EchoPet and Citizens Development build #1428+ are not compatible with each other and are causing entities from both plugins to become invisible. Citizens on its own works fine. As soon as EchoPet is added to the server this can cause all EchoPet pets to become invisible along with some Citizens NPCs. I had this issue with both the Citizens Villager NPC type and the creeper NPC type but there could be more.

**Comment by Borlea** [comment]
From my understanding the citizens dev has done a fix for this. I will also be doing a change to prevent any issues before a stable 1.11 release

**Comment by Borlea** [comment]
It appears @fullwall has done one of the worst things you can do with entity registration in one of his latest commits shown here https://github.com/CitizensDev/Citizens2/commit/765c42cb452451656d17a7ff4c3978205a0c4306#diff-6805fb8e330485c598cf9f9a08a0c774R13

He took a little class from some guy on spigot which only creates more issues rather then fixing anything.

Whoever uses the same system and gets registered last takes full control over the class and results in other plugins having conflict issues. If fullwall wants to provide any information on why he did such thing while also calling it less 'invasive'.

Here is the current way im doing it https://github.com/Borlea/EchoPet/commit/0eece15ae58e1cf1ddbcfed7cae2ea431bc2136a which I think fullwall had something different

**Comment by drekryan** [comment]
Ok thanks for your time and effort looking into this.. I'll see if I can help get Citizens to improve the way they are doing things to prevent further problems. Thanks for your detective work here

**Comment by Borlea** [comment]
It is rather interesting and just takes a bit of time for developers to find the best possible way to keep our plugins working without conflicts of others. But overriding a base nms class isn't the way to go.

**Comment by drekryan** [comment]
Was the PetRegistry Change you made supposed to fix this issue? Or does a change need to be made by Citizens in order to fully fix this?

**Comment by Borlea** [comment]
Was suppose to prevent conflict with other plug-ins doing the say system I used previously. I have no idea the current conflict but I believe it's due to overriding the registry. I will have enough to look into it more later, maybe I can get in contact with full wall on irc to find a proper way to register entities without conflict issues

**Comment by Borlea** [comment]
Created https://github.com/CitizensDev/Citizens2/issues/981 for now.. Lets see if someone will give me a response.

**Comment by drekryan** [comment]
Awesome thank you!

**Comment by mcmonkey4eva** [comment]
Sorry for the trouble, our fault (Citizens team). Should be fixed by end-of-day-ish.

**Comment by drekryan** [comment]
@mcmonkey4eva thanks very appreciated.

**Comment by drekryan** [comment]
This issue appears to be fixed with the latest Citizens development builds
