### ISSUE TITLE
[1.11] Echo Pet fails to generate a valid default configuration

### ISSUE THREAD

**Issue by drekryan** [Borlea/EchoPet#120]
EchoPet fails to generate a valid default configuration when no configurations already exist. A fresh startup of EchoPet with no configuration files will cause files to generate however the /pet select menu will only show the human pet and no other options will appear even though the other pets are set to enabled in the config file.

If you have configuration files from before this was an issue EchoPet loads correctly and shows all the pets.

If you load build #20 for example and have that build generate the configs and then upgrade to build #23 it will work correctly. However you load Build #23 straight away without config files it will not work correctly and show all available pets.

**Comment by TNTUP** [comment]
Reproduced it, I have renamed my config.yml into .yml0 and let Echopet generate an empty config. There's just the human head as @drekryan says.

http://i.qcfb.ca/201611230194539.png

**Comment by drekryan** [comment]
This issue is fixed in the latest build
