### ISSUE TITLE
[1.11] Right clicking a pet causes the mouse cursor/view to move or shift

### ISSUE THREAD

**Issue by drekryan** [Borlea/EchoPet#121]
Right Clicking a pet causes the mouse cursor and your view to shift. The cursor and view should remain in place. For example if im looking at my Llama pet and right click my cursor will shift and my view will change to my back facing the Llama or some other semi-random direction.

**Comment by Borlea** [comment]
A older issue should exist already. But it may be handled on the client. If you know a plugin without the issue with horses/Llamas please link. All the attempts to prevent it have failed

**Comment by drekryan** [comment]
Hmm I'll have to look around and do some research on a solution for this. I do know that during the 1.11 snapshots the llamas originally had a similar issue to this when you tried to feed a llama hay bales for breeding and it was fixed in a later snapshot by Mojang. You are correct that it only appears to happen on horse type pets and the Llama. Unfortunately don't know how they went about fixing it. I could try to catch Grum (Erik Broes) on IRC and see if he may know what could be done.

**Comment by drekryan** [comment]
You can close this issue as a duplicate if you would prefer to track it as #34. Sorry about that. Didn't initially see the issue open.

**Comment by Borlea** [comment]
Closing for #34
