### ISSUE TITLE
[1.11] Vex Pet flies into the ground

### ISSUE THREAD

**Issue by drekryan** [Borlea/EchoPet#122]
The Vex pet always flies or drops into the ground. The pet should fly above ground and behind the player. While the pet is below the ground it is also not possible to interact with it such as right clicking it.

**Comment by Borlea** [comment]
The pet does fly kind of.. it needs some fixing still. But you have to generate a new configuration or set its properties up like the blaze. But apparently Config generating is broken

**Comment by drekryan** [comment]
Fixed as of commit 36809be
