### ISSUE TITLE
Mob eggs are all displayed the same / without data values in the pet selector GUI.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#126]
EchoPets dev 26
http://jenkins.codingforcookies.com/job/EchoPet/job/Minecraft-1.11
PaperSpigot dev 933 (MC 1.11)
https://ci.destroystokyo.com/

New config.
![link](http://i.imgur.com/mhNQeCe.png)

Is it at all possible to have specific mob eggs displayed in the GUI again? I know the specific data values for each individual monster egg was removed in 1.9 (or 1.10, can't remember), so may need an alternate way to specify / display.

**Comment by Borlea** [comment]
Definitely not a new config if all the eggs are white. That was fixed already

**Comment by mibby** [comment]
I deleted the EchoPets folder to let it regenerate when testing. So should be a new config. Tested as of this commit https://github.com/Borlea/EchoPet/commit/e471349e0b9a8eb0e6de8e1b6bfc9e59621dc95c unless you just recently pushed a fix for it with pagination.

**Comment by Borlea** [comment]
Latest build will have the page system. which from testing works and has colored eggs.

**Comment by mibby** [comment]
I regenerated a new config again on dev 27. All seems good now. 👍
