### ISSUE TITLE
/pet select not working

### ISSUE THREAD

**Issue by SecretlyJealous** [Borlea/EchoPet#133]
Error: http://hastebin.com/alohotucaf.sql
Version: EchoPet v1.0.4-SNAPSHOT-b36

**Comment by dordsor21** [comment]
can confirm. Using build 24 from master jenkins branch (latest master version)

**Comment by drekryan** [comment]
Looks like a null pages issue again? Did you both regenerate the config files?

**Comment by SecretlyJealous** [comment]
Regenerating the config file fixed the issue, thanks!
