### ISSUE TITLE
Unable to ride pet.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#137]
@Borlea 

PaperSpigot dev 953 (MC 1.11)
EchoPet dev 27

You are unable to ride any pet. Tried both command ```/pet ride``` and GUI based clicking the ride option. It outputs the message in chat that you are riding your pet, but you are not visibly riding. The pet just sits besides you still.

**Comment by TheIntelloBox** [comment]
I confirm this bug.

**Comment by Borlea** [comment]
Fixed in https://github.com/Borlea/EchoPet/commit/9bd1f5c6156ae1e22cca1d77e5d2cf55c08f43dd Accidently put wrong issue number.

**Comment by mibby** [comment]
Thanks. Seems to be working fine as of dev 31.
