### ISSUE TITLE
Pet horse crashes the client.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#14]
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 3/11/16 8:16 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at wk.o(SourceFile:222)
	at wk.dm(SourceFile:301)
	at wk.cf(SourceFile:852)
	at sa.n(SourceFile:1745)
	at sb.n(SourceFile:488)
	at ro.n(SourceFile:134)
	at vw.n(SourceFile:41)
	at wk.n(SourceFile:887)
	at sa.m(SourceFile:1615)
	at sb.m(SourceFile:276)
	at wk.m(SourceFile:920)
	at aht.a(SourceFile:1515)
	at aht.g(SourceFile:1493)
	at aht.k(SourceFile:1383)
	at bcf.t(SourceFile:1641)
	at bcf.av(SourceFile:962)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at wk.o(SourceFile:222)
	at wk.dm(SourceFile:301)
	at wk.cf(SourceFile:852)
	at sa.n(SourceFile:1745)
	at sb.n(SourceFile:488)
	at ro.n(SourceFile:134)
	at vw.n(SourceFile:41)
	at wk.n(SourceFile:887)
	at sa.m(SourceFile:1615)
	at sb.m(SourceFile:276)
	at wk.m(SourceFile:920)
	at aht.a(SourceFile:1515)
	at aht.g(SourceFile:1493)

-- Entity being ticked --
Details:
	Entity Type: EntityHorse (wk)
	Entity ID: 54904
	Entity Name: Horse Pet
	Entity's Exact location: 3212.13, 91.00, -14.18
	Entity's Block location: World: (3212,91,-15), Chunk: (at 12,5,1 in 200,-1; contains blocks 3200,0,-16 to 3215,255,-1), Region: (6,-1; contains chunks 192,-32 to 223,-1, blocks 3072,0,-512 to 3583,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at aht.k(SourceFile:1383)

```

**Comment by Borlea** [comment]
Can you do more tests with latest build [here](http://jenkins.codingforcookies.com/job/EchoPet/). Still unable to reproduce the bugs you are finding.

**Comment by Nickshelton80** [comment]
I too am crashing when I try to spawn in the reported mobs.

I am using build #5 from that CI server you linked and the latest spigot.

**Comment by Nickshelton80** [comment]
Edit: I'm really confused now, all I did was install another plugin (CrateKeys....) and now my client isn't crashing anymore when they spawn in...

However: Horses/Villagers are invisible and pets don't turn into babies.

**Comment by Nickshelton80** [comment]
I was initially testing on craftbukkit where I had all of the issues mibby reported.

I then moved to spigot, where everything was functional. However, my client crashes on 2 of my servers, (they use libsdisquises / citizens).

So it would appear that the conflict is with those plugins and plugins that are similar to them.

**Comment by mibby** [comment]
Why are you marking this as unable to reproduce? I can only assume you aren't testing yourself since this occurs in a clean test environment...

Using EchoPets dev build 5 and _only_ EchoPets plugin with PaperSpigot dev 488, the client crash still occurs when spawning in a pet horse.

**Comment by Nickshelton80** [comment]
@mibby I believe I have figured out why he isn't experiencing it, but you are:

https://github.com/Borlea/EchoPet/issues/26

**Comment by Borlea** [comment]
Can be updated at #12

**Comment by mibby** [comment]
Confirmed fixed.
