### ISSUE TITLE
Unable to teleport while wearing a pet on your head.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#141]
EchoPets dev 31
PaperSpigot dev 958 (MC 1.11)

With a pet on your head, you are unable to teleport. For example, typing /spawn, /home, or /warp. It outputs in chat that you are teleporting (from the various plugins - i.e. EssentialsX), but you do not teleport or move at all.

Removing the pet from your head, you are able to teleport.

**Comment by mibby** [comment]
On a similar note, you _are_ able to teleport while riding a pet. But after teleporting, you are dismounted from the pet.

**Comment by Borlea** [comment]
#87

**Comment by mibby** [comment]
So it is allowed to work when you are able to ride an entity but not while you are used as the vehicle for the pet?

**Comment by Borlea** [comment]
@mibby CraftPlayer.teleport does a check > `ifentity.isVehicle()){`
Which is true if an entity is riding you(a pet)
I have no clue why they allow you to teleport when riding a vehicle though. But they do `entity.stopRiding();` in the teleport method

Spigot could just loop the people riding the vehicle and call the stopRiding method.. but its not an issue I can fix, someone can maybe do a pr?

**Comment by Pokechu22** [comment]
Quoting from [here](https://www.reddit.com/r/admincraft/comments/5p0mq0/if_you_could_change_somethings_about_spigot/dcoywxo/?context=3):

> Running a `git blame` on that line gives me `71b0510f`.
> 
>     $ git show -s 71b0510f
>     commit 71b0510f88d1edf31dd8d823e4035f0b508c735f
>     Author: feildmaster <admin@feildmaster.com>
>     Date:   Tue Nov 20 18:15:00 2012 -0600
>     
>         Fix teleporting entities with vehicles/passengers teleporting you illegally. Fixes BUKKIT-2821
>         
>         Also some formatting...
> 
> Unfortunately the bukkit tracker isn't available, but it was fortunately [archived](https://web.archive.org/web/20160322092430/https://bukkit.atlassian.net/browse/BUKKIT-2821).  At that time, the check was `(entity.vehicle != null || entity.passenger != null)`.
> 
> It was changed to `isVehicle()` in the 1.9 update (`aa008dff` - the need for the change multiple passangers), but prior that it had been changed before, in `a4805dbd`:
> 
>     $ git show -s a4805dbd
>     commit a4805dbd77da057cc1ea0bf344379bc6e53ca1f6
>     Author: bendude56 <bendude56@gmail.com>
>     Date:   Sun Jul 7 21:52:41 2013 -0600
>     
>         Allow teleportation of entities on vehicles. Fixes BUKKIT-4210
>         
>         Up until Minecraft version 1.5 it was not possible to teleport entities
>         within vehicles. With the 1.5 update came the change in the Minecraft
>         teleportation logic to dismount before teleporting the entity, if
>         applicable.
>         
>         This commit ammends the existing CraftBukkit logic for rejecting
>         teleportation for entities in vehicles to permit the action. Due to this
>         change, CraftBukkit is now in-line with Minecraft 1.5 teleportation logic.
> 
> Sadly, BUKKIT-4210 is not archived, so I have no idea of the details.  But the check (at the time it was added) did not exist for no reason; that reason should probably be re-evaluated now though to see if it _is_ safe to teleport.

I'm going to mess with this and see if I can figure out if it's still broken to teleport entities like this.  I don't think it is, but there's still a risk; if it is safe I'll submit a PR to bukkit to remove the check.
