### ISSUE TITLE
Update pom craftbukkit dependency to correct version.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#15]
https://github.com/Borlea/EchoPet/blob/Minecraft-V1.9/modules/v1_9_R1/pom.xml#L60

To ```1.9-R0.1-SNAPSHOT```.

**Comment by Borlea** [comment]
As noted [here](https://github.com/Borlea/EchoPet/commit/d160e2a81b70fafd764aa3690db6e50953d07d18#commitcomment-16659864) this wont happen.

**Comment by mibby** [comment]
You would be forcing users to put a craftbukkit jar in a '1.9' repository folder. Whereas if you build craftbukkit normally with buildtools, it properly places the latest version '1.9-R0.1-SNAPSHOT' in the repo. It is better to seek the correct dependency.

**Comment by Borlea** [comment]
Ah so it does...
