### ISSUE TITLE
BUG: Could not pass CreatureSpawnEvent

### ISSUE THREAD

**Issue by ItsAZZA** [Borlea/EchoPet#150]
Hey, I have been using CommandHelper on my server, and whenever a player spawns in an entity with EchoPet a following error occurs: https://hastebin.com/esupubanoy.vbs

Haven't encountered this problem with other plugins so this is only a problem with EchoPet, using the latest version.

But correct me if I am wrong. Thanks already for your answer.

**Comment by Borlea** [comment]
That is an issue related to CommandHelper and isn't something I can solve.

**Comment by ItsAZZA** [comment]
Okay, thanks for your answer!

**Comment by ItsAZZA** [comment]
I got this from him:
"EchoPet spawns all entities with an UNKNOWN entity type. So it might look like a Polar Bear, but Bukkit doesn't know that apparently. It turns out CH doesn't handle entities with an UNKNOWN entity type specifically enough, like with CreatureSpawnEvent expecting a LivingEntity. I submitted a change to force it to do so."

**Comment by Borlea** [comment]
I'll continue any discussion over here https://github.com/EngineHub/CommandHelper/pull/446
