### ISSUE TITLE
Ticking player crash

### ISSUE THREAD

**Issue by SecretlyJealous** [Borlea/EchoPet#151]
Crash: https://hastebin.com/ujeregosej.scala
Version: EchoPet v1.0.4-SNAPSHOT-b39

**Comment by Borlea** [comment]
Due to it being entirely in minecrafts code I'm unable to determine what is happening on line 1086 in Entity.java and causing this error.

I'm assuming this isn't an issue related to EchoPet and marking it as invalid.

An extra note I guess updating to 1.11.2
