### ISSUE TITLE
EnderDragon

### ISSUE THREAD

**Issue by HeadlessJoey** [Borlea/EchoPet#153]
Spigot 1.11.2
Latest dev build number 41
No errors or anything

The enderdragon controls for flying it/riding it are broken.
It gets stuck in the ground also so you can't ride/fly it anywhere and if you do manage to not get it stuck in the ground then the controls are wrong: 
left and right = forward
forward = left
backwards = backwards

**Comment by Borlea** [comment]
Prob not fixing the get stuck thing.. Since that is due to it being able to no clip, and no clip being disabled when riding it.

Looked into the movement and I don't know the issue so I'm ignoring it.

**Comment by HeadlessJoey** [comment]
Thanks, build 43 fixed this.
