### ISSUE TITLE
Pets going into worlds with no permission

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#157]
Having a bit of a problem, haven't fully looked into it, but can you check this out for us:
https://www.ecocitycraft.com/forum/threads/bug-report-pet-in-sg.160885/

If more info is needed I can get that from @jamiesinn in a few days.
We are currently using echopet build 39 from your Jenkins.

**Comment by JamieSinn** [comment]
RE: https://github.com/Borlea/EchoPet/issues/28

**Comment by andrewkm** [comment]
Closing so we can use other ticket.

**Comment by Borlea** [comment]
#28 is not an issue related to this

**Comment by Borlea** [comment]
The 'Pets are not allowed here.' is only sent on specific cases.

If a PlayerTeleportEvent is being called on a pet owner, or attempting to spawn a pet.

This would not get spammed unless one of these actions was being spammed.

**Comment by Borlea** [comment]
Due to how most SG plugins work they mass warp the player before the round starts. And with the pet still being loaded for the player still, each time the player gets warps it would spam it, https://github.com/Borlea/EchoPet/commit/13568ec4556e8d03fa7f45ba41a3d775ccbd566b should fix this.

**Comment by andrewkm** [comment]
This is fixed. Thank you :)
