### ISSUE TITLE
Update WorldGuard hook detection for dev build compatibility.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#16]
https://github.com/DSH105/EchoPet/issues/595
https://github.com/DSH105/EchoPet/issues/596

http://builds.enginehub.org/job/worldguard

https://github.com/Borlea/EchoPet/blob/Minecraft-V1.9/modules/EchoPet/src/com/dsh105/echopet/hook/WorldGuardProvider.java#L36

6.0 -> 6.1.2

https://github.com/Borlea/EchoPet/blob/Minecraft-V1.9/pom.xml#L74

Compile with 6.1.2 instead of 6.1.1 as well?

**Comment by Borlea** [comment]
No issue here with loading 6.1.2
[proof](http://goo.gl/uvADY0)
6.1.2 is currently a dev build, and because we support 6.0 we should be building off 6.0(which we aren't even doing and will be fixed.)
