### ISSUE TITLE
No PlayerMoveEvent fired when pets move with rider

### ISSUE THREAD

**Issue by 10becja** [Borlea/EchoPet#166]
It appears that while riding pets, the PlayerMoveEvent is not fired for the rider. This results in players being able to ride pets into places they wouldn't be able to get into otherwise, such as a WorldGuard region that they've been denied entry, or from other plugins that allow for blocking movement into areas. Not sure if it's possible or not to fire that event when the pet moves, but if so it would be very helpful to prevent trolling.

Vanilla animals that you can ride, such as horses pigs and llamas, don't seem to have this problem: the player is properly removed. 

If it's not possible, any suggestions on how to track pet movement would be appreciated and I can try modifying my plugins to account for it. Thanks!

**Comment by Borlea** [comment]
https://github.com/Borlea/EchoPet/blob/master/modules/API/src/com/dsh105/echopet/compat/api/event/PetMoveEvent.java

**Comment by 10becja** [comment]
This event only seems to fire when the pet is following the owner. It doesn't appear to ever fire when the pet is being ridden. As far as I can tell, the only places it looks like it's being created is in PetGoalFollowOwner class.

**Comment by Borlea** [comment]
Oops wrong one, PetRideMoveEvent

**Comment by 10becja** [comment]
Perfect, worked like a charm. Thanks!
