### ISSUE TITLE
There's no version 3.1 of maven-assembly-plugin

### ISSUE THREAD

**Issue by Mstrodl** [Borlea/EchoPet#18]
When I try to build this, I get the error:
> [INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).
>

> Project ID: org.apache.maven.plugins:maven-assembly-plugin

> Reason: POM 'org.apache.maven.plugins:maven-assembly-plugin' not found in repository: Unable to download the artifact from any repository

>   org.apache.maven.plugins:maven-assembly-plugin:pom:3.1

> from the specified remote repositories:
  elmakers-repo (http://maven.elmakers.com/repository/),
  kitteh-repo (http://repo.kitteh.org/content/groups/public),
  central (https://repo1.maven.org/maven2),
  sk89q-repo (http://maven.sk89q.com/artifactory/repo/),
  yawkat-repo (http://mvn.yawk.at/),
  vault-repo (http://nexus.theyeticave.net/content/repositories/pub_releases),
  hawk-repo (http://ci.hawkfalcon.com/plugin/repository/everything/),
  dmulloy2-repo (http://repo.dmulloy2.net/content/repositories/snapshots/),
  spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/),
  codingforcookies-repo (http://repo.codingforcookies.com/)

> for project org.apache.maven.plugins:maven-assembly-plugin

I looked in the `pom.xml` file and saw that you have the version set to 3.1. I can't find any reference to a version newer than 2.6 anywhere. Am I missing something here?

**Comment by Borlea** [comment]
I might of updated the wrong plugin, thanks for the report I'll set it to 2.6

**Comment by Mstrodl** [comment]
Ok, Thanks. I guess I'll get rid of the sed command on my CI :)
