### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ridalarry** [Borlea/EchoPet#24]
I have checked that there are many forks for EchoPet and I would like to suggest having a look at them in the glitched parts to see how they fixed it and you could use it on this version. I am not sure if any of them has updated anything, but having a look at it would help.

https://github.com/RarePika/EcoCityPet/
https://github.com/MegaCrafting/MegaPets-EchoPet-remade-
https://github.com/TechzoneMC/SonarPet

**Comment by Borlea** [comment]
I have a bit of contact with EcoCityPet, seems to be doing his own thing mostly.

Other two have pretty much zero progress on 1.9, first one seems to only have switched from 1.8 to 1.9 imports

**Comment by ridalarry** [comment]
Thank you for your fast response I will close this as its not really an issue, but I would like to know if you are planning to release it?

**Comment by Borlea** [comment]
You can grab a development build which seems to mostly work(potentially a few client crashes & lots of console errors) and you may also experience what mibby is experiencing where a lot more things are broken for some reason(He seems to be the only one to have reported the issue though).

**Comment by ridalarry** [comment]
My server isn't on 1.9 yet, but I want to, so I am waiting for 1.9 to be stable from mojang and spigot, all plugins get updated and optifine version of 1.9 as most of the players won't play without optifine. I will try to test the plugin out and report bugs if I found any.
