### ISSUE TITLE
Certain Pets causing client crash while in world with other entities.

### ISSUE THREAD

**Issue by Nickshelton80** [Borlea/EchoPet#26]
- removed -

**Comment by Nickshelton80** [comment]
Okay actually.. It's my servers that do not have mobs on them that are fine.

Example: Everything is functional on my hub/creative server since there are no entities.

On my towny/creative/factions/skyblock servers, horse/rabbit/wolf/ocelot pets crash the client.

**Comment by Nickshelton80** [comment]
Somethings I tested to add:

While running echopet:
If you do /spawnmob wolf (via essentials or anything else) your client crashes. (/pet wolf crashes you as well of course)

Without running echopet.
If you do /spawnmob wolf your client will not crash.

It's almost like it isn't being distinguished if it's a normal wolf or not. I assume that's what the data watcher is about.

Hope this helped :D

**Comment by Borlea** [comment]
Interesting.. I'll see why

**Comment by Borlea** [comment]
I got progress :)
[pic](http://goo.gl/nkIbZC)

Still a lot more work ahead.

**Comment by Nickshelton80** [comment]
Great to hear!

**Comment by Borlea** [comment]
Can this be retested on build [8](http://jenkins.codingforcookies.com/job/EchoPet/8/)

**Comment by Nickshelton80** [comment]
Did a quick test and it looks great so far, I'll be able to test more tomorrow!

**Comment by Borlea** [comment]
According to the results from #12 it has been fixed, thanks for identifying the root problem.
