### ISSUE TITLE
Pet Hide - Server Crash

### ISSUE THREAD

**Issue by Nickshelton80** [Borlea/EchoPet#29]
It seems that one of my servers crashed when someone did /pet hide to their squid.
Log: http://pastebin.com/bJiH6Rd9

Crash report: http://pastebin.com/mpkCVRMv

**Comment by meytro** [comment]
Seems like the issue is fixed.

**Comment by Borlea** [comment]
Seems you have citizens, guessing it is the result of the conflict related to citizens. If the issue stays please recreate the issue.

Fixed here 58c26468464b951637b8648ad61b80e5c347de84
