### ISSUE TITLE
Server Crash - Player joining with bat pet?

### ISSUE THREAD

**Issue by Nickshelton80** [Borlea/EchoPet#33]
Crash Report: http://pastebin.com/zkb37T4w

Error Log when the player logged in: http://pastebin.com/1FwSbh2P

Right before the crash: http://pastebin.com/3h0RtzTk

Looks like it was trying to load the bat pet but ran into an issue.

This was the latest spigot and echopet 6 from the ci server

**Comment by Borlea** [comment]
Can this be retested on the latest [build](http://jenkins.codingforcookies.com/job/EchoPet/)

**Comment by Borlea** [comment]
Same as #42
