### ISSUE TITLE
Screen orientation forcefully resets to the direction of the horse when right clicking a pet horse.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#34]
EchoPets dev 10.

**Comment by Borlea** [comment]
From my investigation it is not possible to fix. I have attempted an failed, but I'll see again

**Comment by mibby** [comment]
:( Any idea why it happens in the first place?

Still occurs on dev 11 for reference.

**Comment by mibby** [comment]
Still an issue as of dev 31 on MC/Spigot 1.11 for horses, donkeys, mules, llamas, etc. Oddly enough, skeleton horse and zombie horse pets don't have this behavior.

**Comment by Borlea** [comment]
Skeleton horses and zombie horses don't open an inventory on right click

**Comment by Borlea** [comment]
This is due to the g(EntityHuman entityhuman) method in EntityHorseAbstract.

Skeleton and zombie horses have a slightly different a(EntityHuman, EnumHand) method (The one that calls g(EntityHuman)). Which is why it doesn't reset like all the other horses.

**Comment by Borlea** [comment]
From my investigation this is handled both on client & server. Nothing can be done about it.

**Comment by mibby** [comment]
So the problem is fundamentally an issue in the MC client / server that can't be overridden? Or is it something that can be fixed upstream in Spigot through nms/API changes?

**Comment by drekryan** [comment]
I actually noticed this as a bug in pure vanilla Minecraft as well.. believe this is something Mojang would need to tackle
