### ISSUE TITLE
Pet rabbit doesn't stop jumping.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#35]
Bug or intended?
EchoPets dev 10.

**Comment by DylanCare** [comment]
This has happened every since the rabbit was added in the original builds. Pretty sure I remember the dev saying it was the only way to make them jump at the time.

**Comment by Borlea** [comment]
He has a delay to make the rabbit jump every one in awhile.. No clue if it's needed or maybe I could find a way to only jump when needed..

**Comment by Borlea** [comment]
Should be all good now, if you encounter any issues recreate the issue.
