### ISSUE TITLE
Pet shulker does not follow the player.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#36]
EchoPets dev 10.

**Comment by Borlea** [comment]
Shulker isn't even a mob that should move and will most likely require some hacky stuff to move.. I'll most likely be removing it in a future build as it causes crashes when putting it as a hat.

**Comment by mibby** [comment]
Alright, probably best to just remove it then. :)

**Comment by Borlea** [comment]
Has been removed in the latest development build(11)
