### ISSUE TITLE
Issues with building repo in Eclpise...

### ISSUE THREAD

**Issue by DylanCare** [Borlea/EchoPet#37]
I've been trying to get this fork setup on my Eclipse so I can fiddle around with it and help out, but I've been pulling my hair out trying to get everything setup correctly. 

Every time I try to build, it fails on the EchoPet API module like so: http://pastebin.com/McKNPJhm

I understand whats wrong, I just don't know how to fix it. Even attempted remaking the pom and got my own Commodus/PowerMessage builds, but still running into issues. 

Sorry if this is the wrong place to ask. I've exhausted google pretty hard.

**Comment by Borlea** [comment]
'(http://repo.dsh105.com/): Too many follow-up requests: 21 '

You are running an old version with dsh105's repo still in the pom..

**Comment by DylanCare** [comment]
See, my problem is that, none of the poms even mention his repo... although it's still trying to build with it. Pretty sure eclipse is just storing some old stuff somewhere. I'll dig around and probably just reinstall M2E real quick.

**Comment by DylanCare** [comment]
I wiped everything that had to do with EchoPet and it's dependencies and reinstalled my maven plugin and deleted all the local data. Still not able to build the project sadly. 

Here's the build log: http://pastebin.com/8kCqCV99

http://repo.codingforcookies.com/ definitely does't have PowerMessage and I have no clue what to do about that

**Comment by Borlea** [comment]
Ohh that explains it.. I just redeployed power message to the repo

**Comment by DylanCare** [comment]
Could you deploy Commodus as well there? As the pom is referencing the same repo(http://repo.codingforcookies.com) for the Commodus dependency as well.

**Comment by DylanCare** [comment]
Thanks! Able to successfully build now :+1:
