### ISSUE TITLE
Giant crashs plugin

### ISSUE THREAD

**Issue by meytro** [Borlea/EchoPet#38]
After trying to create a Giant pet the plugin stops working for all others pets too.

You get this error while spawning a Giant which disappear after 1 second: http://pastebin.com/HMM4N3rt
This error occurs if you try to select a other pet after the Giant: http://pastebin.com/MCe5AHrt

**Comment by Borlea** [comment]
Will be in build 13 whenever it automatically builds. Thanks for the report
