### ISSUE TITLE
Does this Work with 1.9?? (URGENT)

### ISSUE THREAD

**Issue by Pokemon4372** [Borlea/EchoPet#40]
@Borlea **Hi!! This is kinda urgent** So now echopet is discontinued i stumbled on this.. It seems there is many changes to this BUT... is it 1.9 compatible??
If so, can i have a .jar?
Thanks!

**Comment by KingFaris10** [comment]
It is compatible. I've built the latest source code myself and tested, and I have seen no errors so far.

**Comment by Pokemon4372** [comment]
Brilliant!!

**Comment by Pokemon4372** [comment]
@KingFaris10 Have you a .jar file for this version? Please give me a download if so

**Comment by Pokemon4372** [comment]
@KingFaris10 Which one do i make into a jar file? Which would be the best one and which folders do i contain in the jar?

**Comment by KingFaris10** [comment]
The structure of this project is fairly unique. It is not like how you think. Normally, you would just have one project and build it. However this one, you have to create one major project then 3 projects within it (I only know this is achievable by using IntelliJ IDE, no idea how to do it in Eclipse). Then you have to fix quite a few pom.xml errors, and then finally you can build the Parent project. Really, I wouldn't recommend building this project in Eclipse IDE.

**Comment by KingFaris10** [comment]
Forgot to tag, @Pokemon4372

**Comment by Borlea** [comment]
I have it setup in eclipse, not too hard really.. But unless you are modifying the plugin for a PR or something you have no real point in building it yourself you can download it at my [jenkins](http://jenkins.codingforcookies.com/job/EchoPet/). Which every hour checks if any new commits happened, if so it'll make a new build.

**Comment by Pokemon4372** [comment]
@Borlea Thanks for making this version of EchoPet, my server needed it!! I am so happy that someone still cares about the amazing project. :P 
On behalf on my server, once again, Thanks! (and yes i will keep checking the jenkins now i know it exists)

<3

**Comment by KingFaris10** [comment]
@Borlea Oh, I didn't even notice you updated the 'Download' link for this GitHub page. I just assumed it was linking to the old Download page. RIP, I spent a good 30mins trying to install this as I had to fix all the pom.xml's (the current ones weren't working, e.g. the repo link for dsh's libraries)
