### ISSUE TITLE
Error on spawn

### ISSUE THREAD

**Issue by AshourAziz** [Borlea/EchoPet#44]
I'm using the latest off the Jenkins server, and I'm getting these crashes when spawning in pretty much all types of pets.

Also, 

http://pastebin.com/Nn81rzDa
http://pastebin.com/CXuB8nb5

**Comment by Borlea** [comment]
Give me the results of /version and /plugins

**Comment by AshourAziz** [comment]
https://www.ashour.pw/images/160331155210160315521003.png

Could this be because of: https://github.com/ProtocolSupport/ProtocolSupport?

**Comment by Borlea** [comment]
Most likely

**Comment by Borlea** [comment]
Pastebins expired and no further information. If the issue stays please recreate the issue.
