### ISSUE TITLE
Jenkins is dead.

### ISSUE THREAD

**Issue by meytro** [Borlea/EchoPet#48]
For the page http://jenkins.codingforcookies.com/job/EchoPet/ you get the error 
"No 'sona set up for that domain."

**Comment by xknat** [comment]
same

**Comment by Borlea** [comment]
#47 Seems like we still got 1 thing left to setup

**Comment by Borlea** [comment]
Just finished up setting up the new maven.. hopefully the jenkins will be setup tomorrow

**Comment by Sonic5317** [comment]
Any news on this?

**Comment by Borlea** [comment]
You can visit the jenkins [here](http://codingforcookies.com:8080/job/EchoPet/). It is temp until I get my friend to fix the jenkins subdomain

**Comment by xknat** [comment]
> You can visit the jenkins here. It is temp until I get my friend to fix the jenkins subdomain

link is also not working any more (404)

**Comment by Borlea** [comment]
temp changed again http://codingforcookies.com:8090/

**Comment by xknat** [comment]
> temp changed again http://codingforcookies.com:8090/
still not working for me it got blockt
ERR_CONNECTION_REFUSED

**Comment by Mstrodl** [comment]
@Borlea Try `sudo mkdir /var/lib/jenkins/workspace/EchoPet && sudo chown jenkins:jenkins /var/lib/jenkins/workspace/EchoPet -R && sudo chmod 775 /var/lib/jenkins/workspace/EchoPet -R` and running a manual build to see if it works :smile:

**Comment by xknat** [comment]
http://jenkins.codingforcookies.com/job/EchoPet/ seems to work again, but all builds are unsuccessful (so we still cant download)
:-1:

**Comment by mibby** [comment]
@Borlea Yep. Jenkins is up but build fails to compile. :P

Have it compile this fork for the latest dependency change you made?
https://github.com/Borlea/Reflection

```
ERROR] Failed to execute goal on project EchoPet-Parent: Could not resolve dependencies for project com.dsh105:EchoPet-Parent:pom:1: Failed to collect dependencies at com.captainbern:Minecraft-Reflection:jar:1.0.1: Failed to read artifact descriptor for com.captainbern:Minecraft-Reflection:jar:1.0.1: Could not transfer artifact com.captainbern:Minecraft-Reflection:pom:1.0.1 from/to codingforcookies-releases (http://repo.codingforcookies.com/content/repositories/releases/): Failed to transfer file: http://repo.codingforcookies.com/content/repositories/releases/com/captainbern/Minecraft-Reflection/1.0.1/Minecraft-Reflection-1.0.1.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by Borlea** [comment]
@Mstrodl Was actually do to a lack of installing git on the server..

@mibby Maven is setup again ;-;

@xknat should be all good now here http://jenkins.codingforcookies.com/job/EchoPet/

**Comment by Mstrodl** [comment]
@Borlea Good, but which jar should I be using now? `target/EchoPet-shaded.jar` isn't being built on mine.

**Comment by Borlea** [comment]
@Mstrodl I changed the output jar to just EchoPet

So fix your afterbuild thingy to grab target/EchoPet.jar and you should be good.
