### ISSUE TITLE
Pet villager is invisible.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#5]
Funny enough, doesn't crash the client. 
![link](http://i.imgur.com/U8cIOZE.png)

**Comment by Borlea** [comment]
Most likely related to the order of the datawatcher being incorrect which then the profession being sent to the client is not a valid profession.

**Comment by mibby** [comment]
Once again, not sure why you aren't able to reproduce unless you aren't testing yourself. 

Using EchoPets dev build 5 and _only_ EchoPets plugin with PaperSpigot dev 488. Spawning in a villager pet, the entity is entirely invisible.

**Comment by Borlea** [comment]
Can be updated at #12

**Comment by mibby** [comment]
Confirmed fixed.
