### ISSUE TITLE
Riding pets into restricted world guard regions.

### ISSUE THREAD

**Issue by Sonic5317** [Borlea/EchoPet#51]
Currently Echopets are able to access worldguard no entry regions.

Default pigs with saddles are blocked from doing this.
Is there any solution possible for this?

**Comment by Borlea** [comment]
why worldguard why

**Comment by Sonic5317** [comment]
Sound like something that could be fixed? 
Wasn't sure if its an echopet issue or just worldguard.

**Comment by Borlea** [comment]
It should be working as intended in the latest build. If the issue persists please create another issue.
