### ISSUE TITLE
working for MC 1.9.2?

### ISSUE THREAD

**Issue by richardun** [Borlea/EchoPet#56]
Hi, just wondering if your version works for 1.9.  If not, I may be interested in helping to upgrade it, but I see that you've done the most recent work on this so just checking.

Thanks.  
richardun

**Comment by Pokemon4372** [comment]
It works with  1.9.(anything) at the moment

**Comment by richardun** [comment]
Great, thanks... I'll install your version.  Still running original.

**Comment by Mstrodl** [comment]
@richardun , Please close the issue if it's resolved.

**Comment by richardun** [comment]
I haven't tried it yet, but I will soon. Closing this.  Thanks!
