### ISSUE TITLE
Pathfinding is unable to walk up stairs/slabs

### ISSUE THREAD

**Issue by Borlea** [Borlea/EchoPet#58]

**Comment by Dafnik** [comment]
On Minecraft 1.10 or 1.9?

**Comment by Borlea** [comment]
Confirmed in 1.9, no clue if it's fixed in 1.10

**Comment by Dafnik** [comment]
Later on this day I can post a code for a thread which adds pet following a user. I will try to make a pull request with the solution.

**Comment by Borlea** [comment]
Worked fine in older testing.
