### ISSUE TITLE
Update to 1.10

### ISSUE THREAD

**Issue by Borlea** [Borlea/EchoPet#68]
Initial Support is done.. seems to work fine from my limited testing.

Need to add Husks and Polar Bears which will be done tomorrow(9th)
Will also be adding the ability to change the zombie villager profession as it's the same way for Husks #49 

Pushed the current 1.10 stuff, will be adding the new 1.10 features now

**Comment by mibby** [comment]
Will test as soon as it is pushed to the repo. :)
