### ISSUE TITLE
EchoPet compiled bugs

### ISSUE THREAD

**Issue by SecretlyJealous** [Borlea/EchoPet#71]
I recently started to allow my donators to have more freedom with pets and noticed some issues; just going to address them here in case you're not already aware.

The wildcard permissions such as echopet.pet.ride.* and echopet.pet.hat.* are not working for polarbears, I have to set echopet.pet.ride.polarbear and echopet.pet.hat.polarbear

When doing /pet hat with polarbears or any type of pet it sometimes works since the pet is above your head but after moving around for a few seconds it disappears for yourself but other users can still see it however the plugin still thinks you have the pet on your head so doing any command including /spawn doesn't work but acts like it does because the message still goes through (You have been teleported to spawn) I guess the main issue here is that after walking for a few seconds you can't see your own pet hat which is confusing because people can't get any command to work not realising that they still have their pet hat but can't see it.

Is there a possibility that being able to spawn a baby polarbear could become a feature? I think it would be really nice to have that since other pets also allow you to spawn a baby version. /pet select also doesn't show polarbears, could that be added too?

/pet menu for horse: Chested option does not work and can't change colour to "brown"

**Comment by Borlea** [comment]
Chested option only works for mules and donkeys.

/pet select does show the polar bear. You may need to add it to a slot in the config or just get a brand new config.

I'll add standing up and baby options for the polarbear.

The hat issue is most likely an issue due to mojang not fixing multiple bugs with passengers.

I have fixed the permissions for polarbears, and giants for the next update.

**Comment by SecretlyJealous** [comment]
Is it possible to remove the chested option from displaying in the GUI for horses? Not really important but confusing to players.

I didn't realise the config file stored the pet select information so I got a new config, thanks for telling me about that.
