### ISSUE TITLE
Polarbear permissions

### ISSUE THREAD

**Issue by SecretlyJealous** [Borlea/EchoPet#73]
I give this permission
- echopet.pet.type.polarbear.*
but users can't make polarbears stand up, I'm guessing it's a similar issue to before?

**Comment by Pokemon4372** [comment]
As above, had the same problem

**Comment by Borlea** [comment]
Can this be testing with Build 21 http://jenkins.codingforcookies.com/job/EchoPet/21/

**Comment by Borlea** [comment]
Due to no update I will be closing this as it should be working as intended after build 21. If the issue persists please create another issue.
