### ISSUE TITLE
Log File destroyed (over 1 million lines)

### ISSUE THREAD

**Issue by Bodyash** [Borlea/EchoPet#74]
http://pastebin.com/VcL22kff
Endless spam.

**Comment by Borlea** [comment]
nice infinite loop

**Comment by Bodyash** [comment]
:smile_cat:

**Comment by Borlea** [comment]
To me the issue looks like its attempting to spawn a pet in an area and attempts to teleport  the pet to the owner but something is preventing the pet from properly spawning.

If this still happens after the next build I will need any info you can give.. I need to pinpoint the cause

**Comment by Bodyash** [comment]
I think some /randomteleport  plugin crash my server and that is the reason. Anyway - ty for feature fixing.
