### ISSUE TITLE
Stacked pets issue.

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#82]
We are using build 31
https://www.ecocitycraft.com/forum/threads/bug-report-stacked-pets-pet-rider-names.153342/

**Comment by Borlea** [comment]
That bat failing to teleport death sound really woke me up.. I'll see what I can do about that, the names will take a bit longer

**Comment by Borlea** [comment]
It seems all data related to the pet gets lost on teleport.. hmm

**Comment by Borlea** [comment]
Pets teleporting with a rider should now work.
Riders should now keep their respected petdata & name on teleport.

But it seems someone didn't pay for the maven/jenkins server and it's down ;-;

**Comment by Borlea** [comment]
@andrewkm Jenkins is back up, can you please report back if the issues are fixed.

**Comment by andrewkm** [comment]
wtf, why was this repo on "ignore" no wonder I didn't get notifications.
Thanks, will report back when tested :)

**Comment by andrewkm** [comment]
@borlea sorry been away past 24 hours, confirmed fixed :)
