### ISSUE TITLE
Glitched out cats?

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#84]
Got this report just recently:
https://www.ecocitycraft.com/forum/threads/bug-spastic-imaginary-kitten.153663/

**Comment by Borlea** [comment]
Might be due to the messed up pathfinding on slabs & stairs.. I'll look into fixing that and maybe this will issue will be resolved.. No clue though really

**Comment by Borlea** [comment]
I decided to look into this while I was waiting for a vps to install.. I'm unable to reproduce any issues with ocelots & slabs, it even looks like pathfinding works when it use to not in an earlier 1.10 test..

**Comment by andrewkm** [comment]
Not experiencing this anymore on 1.11.2 and your latest build.
