### ISSUE TITLE
All eggs look the same in Pet Selector

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#85]
Here is the default config from SonarPets and how they are doing it:
(Although his plugin is still completely messed up with pets lol)
http://pastie.org/private/rmgtss2javnemwtl2r29q

**Comment by andrewkm** [comment]
Needs Material ID and Material Data.

**Comment by Borlea** [comment]
My version of EchoPet does support the new spawn egg system introduced in 1.9. It requires certain data from the config which SonarPets/An older version of EchoPet will not create. I suggest you open up a local server with my EchoPet and grab the required data from it.

It should be the property entityName under menu.slot-#

**Comment by andrewkm** [comment]
Your default config just shows MONSTER_EGG, I'm confused.

**Comment by andrewkm** [comment]
so would changing to this work:

>       lore: []
>     slot-4:
>       command: pet chicken
>       petType: CHICKEN
>       material: MONSTER_EGG
>       entityName: Chicken
>       name: Chicken Pet
>       lore: []
>     slot-5:
>       command: pet cow
>       petType: COW
>       material: MONSTER_EGG
>       entityName: Cow
>       name: Cow Pet
>       lore: []
>     slot-6:
>       command: pet creeper
>       petType: CREEPER
>       material: MONSTER_EGG
>       entityName: Creeper
>       name: Creeper Pet
>       lore: []

**Comment by Borlea** [comment]
Yes. because it uses entityName to properly set the monster egg type.
And use material for the material

**Comment by andrewkm** [comment]
Shittttttt..... bless your soul m8 <3

**Comment by andrewkm** [comment]
So with what I use I got this:
http://i.imgur.com/xk0lnMX.png

The ones still showing default eggs are:
Ocelot, Mushroom cow, Cave Spider, Pig Zombie, Magma Cube, Horse.

My pet slots:
http://pastie.org/pastes/10900640/text?key=r8t9oghgmmlfapwgxkqig

**Comment by andrewkm** [comment]
Oh, polar bears show default egg as well =P
(Just added them).

**Comment by Borlea** [comment]
It seems someone did a spelling error in either Spigot/Bukkit or minecraft. They call Ocelot Ozelot.

Mushroom cow should just be 'MushroomCow' without a space. Which seems to be the case for your other 3.

And it seems someone made another mistake and made it so Horse is 'EntityHorse'

**Comment by andrewkm** [comment]
@borlea I just basically copied your default generated config.

**Comment by Borlea** [comment]
I might of changed something resulting in that since my config is a bit old, but works.

**Comment by andrewkm** [comment]
Can confirm all fixed except Magma Cube:
Using:       entityName: MagmaCube

**Comment by Borlea** [comment]
Change it to "LavaSlime"

Seems I got some fixing to do..

**Comment by andrewkm** [comment]
Yeah, just figured out the LavaSlime thing, haha weird naming oh man..
Anyways all fixed, epic support man much love!
