### ISSUE TITLE
Clicking on the slime/magma slime size variant in the pet menu resets mouse position forcefully.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#9]

**Comment by Borlea** [comment]
Due to a closing an inventory then opening a new one

Will be fixed when I redo parts of the guis

**Comment by mibby** [comment]
Also occurs when toggling ocelot cat type.

**Comment by Borlea** [comment]
Will occur with anything with multiple guis that open in a row.

**Comment by Borlea** [comment]
Should be fixed in build 3.

**Comment by mibby** [comment]
Confirmed fixed.
