### ISSUE TITLE
Cats spazzing out.

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#93]
https://www.ecocitycraft.com/forum/threads/bug-spastic-imaginary-kitten.153663/

Not sure if this is something that EchoPet can fix on it's end however. Just making an issue for it in case it is.

**Comment by Borlea** [comment]
Duplicate of #84

**Comment by andrewkm** [comment]
Oh my bad literally forgot I made a ticket on this before. Sorry @borlea
