### ISSUE TITLE
UTF-8/ANSI support

### ISSUE THREAD

**Issue by Xeahnotto** [Borlea/EchoPet#94]
Please give us the UTF-8 and/or ANSI support for translations... ;(

**Comment by Borlea** [comment]
The configs should already support UTF-8.. I did notice reloading the config didn't support UTF-8 which I have fixed.

**Comment by Borlea** [comment]
@Xeahnotto if you can try build 45 of echopet. http://jenkins.codingforcookies.com/job/EchoPet/45/

It has support for UTF-8 on reloading, the only time it shouldn't support utf-8 is if it fails to load the config

**Comment by Borlea** [comment]
Due to such a long absence of response I'm closing the issue.
