### ISSUE TITLE
Two malfunctioning pet types

### ISSUE THREAD

**Issue by Sparclen** [Borlea/EchoPet#96]
There's an issue with 2 rabbit types:

**1.** echopet.pet.type.rabbit.killerbunny just spawns a echopet.pet.type.rabbit.brown, for some reason, instead of a killer bunny.
**2.** echopet.pet.type.rabbit.gold is missing. It's not in any documentation, doesn't show up in the ingame /pet list, and it doesn't recognize it as a valid RabbitType when used in a command.

**Comment by Borlea** [comment]
I just added the gold rabbit type, the killer bunny has been broken for awhile and it's not really a priority for me.

**Comment by Sparclen** [comment]
Thanks for the quick fix!
Shame about the killer bunny, but I suppose its mechanics are a lot different from the regular ones, so I understand.

**Comment by Sparclen** [comment]
'Not really a priority'
Fixed within a day.

You're the boss man, thank you!

**Comment by Borlea** [comment]
Got bored of my other projects and decided to look into it again..
