### ISSUE TITLE
Mooshroom and Polar Bear are Silent

### ISSUE THREAD

**Issue by Internetpilot** [Borlea/EchoPet#98]
Both the Mooshroom and Polar Bear do not make any sounds.  The Mooshroom used to, but the Polar Bear (which is of course new and recently added) never has.  Thanks!

**Comment by Borlea** [comment]
Seems mojang doesn't know what consistency is. It's an issue with the usage of underscores.

iron golem doesn't use an underscore.
mooshroom seems to use cow sounds.. shouldn't be hard
magma cube doesn't use an underscore..

Shouldn't be hard tho
